name: Code scanning for all apps

#
# Scan the code using CodeQL whenever new commits are pushed to the main branch
# or whenever any activity happens inside a pull request targeting the main
# branch. This workflow will only be executed if at least one modified file
# resides outside the "docs" subdirectory and is not directly under the
# repository's root directory.
#
on:
  push:
    branches: [main, dynamic-language-configuration]
    paths-ignore:
    - 'docs/**'
    - '*'
  pull_request:
    branches: [main]
    paths-ignore:
    - 'docs/**'
    - '*'
  schedule:
    - cron: "35 13 * * 2"
  workflow_dispatch:


jobs:
  generate-dir-list:
    # Find all the top level directories in the repostiory and use them for the scan
    # when the workflow is not triggered by a pull_request
    #
    if: ${{ github.event_name != 'pull_request'}}
    name: Generate directory list
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.set-matrix.outputs.matrix}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Find existing directories
        id: set-matrix
        run: |
          echo "::set-output name=matrix::$(./.github/scripts/list-all)"



  generate-changed-dir-list:
    # Find only the changed top level directories and use them for the scan
    # when the workflow is triggered by a pull_request
    #
    if: ${{ github.event_name == 'pull_request'}}
    name: Generate changed directory list
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.set-matrix.outputs.matrix}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Find changed apps
        id: set-matrix
        run: |
          git diff --name-only origin/$GITHUB_BASE_REF $GITHUB_SHA >./.github/scripts/diff.txt
          echo "::set-output name=matrix::$(./.github/scripts/list-changed)"

      - name: Upload diff as artifact
        uses: actions/upload-artifact@v2
        with:
          name: diff
          path: |
            ./.github/scripts/diff.txt
            


  codeql-all-dirs:
    name: Scanning ${{matrix.target-dir}} (${{ matrix.languages }}) with CodeQL
    needs: generate-dir-list
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-dir-list.outputs.matrix) }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    #
    # Build the configuration file for CodeQL to instruct it to only scan the
    # contents of a single directory. For more information about the
    # configuration options available, visit:
    #
    # https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#using-a-custom-configuration-file
    #
    - name: Build CodeQL config file
      env:
        TARGET_DIR: ${{ matrix.target-dir }}
      run: |
        cp .github/codeql/codeql-config-template.yml codeql-config.yml
        sed -i 's@__TARGET_DIR__@'"$TARGET_DIR"'@' codeql-config.yml

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        config-file: codeql-config.yml
        languages: ${{ matrix.languages }}

    - name: Perform CodeQL analysis
      uses: github/codeql-action/analyze@v1
      with:
        category: ${{ matrix.target-dir }}-${{ matrix.languages }}



  codeql-changed-dirs:
    name: Scanning ${{matrix.target-dir}} (${{ matrix.languages }}) with CodeQL
    needs: generate-changed-dir-list
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-changed-dir-list.outputs.matrix) }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    #
    # Build the configuration file for CodeQL to instruct it to only scan the
    # contents of a single directory. For more information about the
    # configuration options available, visit:
    #
    # https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#using-a-custom-configuration-file
    #
    - name: Build CodeQL config file
      env:
        TARGET_DIR: ${{matrix.target-dir}}
      run: |
        cp .github/codeql/codeql-config-template.yml codeql-config.yml
        sed -i 's@__TARGET_DIR__@'"$TARGET_DIR"'@' codeql-config.yml

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        config-file: codeql-config.yml
        languages: ${{ matrix.languages }}

    - name: Perform CodeQL analysis
      uses: github/codeql-action/analyze@v1
      with:
        category: ${{ matrix.target-dir }}-${{ matrix.languages }}
